=== mebigfatguy/fb-contrib/etc/findbugsplugin.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:simpleType name="ClassType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z_][A-Za-z0-9_]*(.[A-Za-z_][A-Za-z0-9_]*)*"/> 
		</xsd:restriction>
	</xsd:simpleType>
		
	<xsd:simpleType name="SpeedType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="fast"/>
			<xsd:enumeration value="moderate"/>
			<xsd:enumeration value="slow"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="BugPatternListType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z0-9_]*(,[A-Za-z0-9_]*)*"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="IdentifierType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Za-z0-9_]*"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="CategoryType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CORRECTNESS"/>
			<xsd:enumeration value="I18N"/>
			<xsd:enumeration value="MALICIOUS_CODE"/>
			<xsd:enumeration value="MT_CORRECTNESS"/>
			<xsd:enumeration value="PERFORMANCE"/>
			<xsd:enumeration value="BAD_PRACTICE"/>
			<xsd:enumeration value="STYLE"/>			
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="DetectorType">
		<xsd:attribute name="class" type="ClassType"/>
		<xsd:attribute name="speed" type="SpeedType"/>
		<xsd:attribute name="reports" type="BugPatternListType"/>
		<xsd:attribute name="requirejre" type="xsd:string"/>
		<xsd:attribute name="disabled" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="hidden" type="xsd:boolean" use="optional"/>
	</xsd:complexType>
	
	<xsd:complexType name="BugPatternType">
		<xsd:attribute name="abbrev" type="IdentifierType"/>
		<xsd:attribute name="type" type="xsd:ID"/>
		<xsd:attribute name="category" type="CategoryType"/>
		<xsd:attribute name="experimental" type="xsd:boolean" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="DetectorCategoryType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="reporting"/>
			<xsd:enumeration value="training"/>
			<xsd:enumeration value="interprocedural"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="SingleDetectorSelectorType">
		<xsd:attribute name="class" type="ClassType" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="DetectorCategorySelectorType">
		<xsd:attribute name="name" type="DetectorCategoryType" use="required"/>
		<xsd:attribute name="spanplugins" type="xsd:boolean" use="optional" default="false"/>
	</xsd:complexType>

	<xsd:complexType name="OrderingConstraintType">
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="Earlier" type="SingleDetectorSelectorType"></xsd:element>
				<xsd:element name="EarlierCategory" type="DetectorCategorySelectorType"></xsd:element>
			</xsd:choice>
			<xsd:choice>
				<xsd:element name="Later" type="SingleDetectorSelectorType"></xsd:element>
				<xsd:element name="LaterCategory" type="DetectorCategorySelectorType"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="OrderingConstraintListType">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="SplitPass" type="OrderingConstraintType"></xsd:element>
				<xsd:element name="WithinPass" type="OrderingConstraintType"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="FindBugsPluginType" mixed="true">
		<xsd:sequence>
			<xsd:element
				name="OrderingConstraints"
				type="OrderingConstraintListType"
				minOccurs="0"
				maxOccurs="1"/>
			<xsd:element name="Detector" type="DetectorType" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="BugPattern" type="BugPatternType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="pluginid" type="xsd:string"/>
		<xsd:attribute name="defaultenabled" type="xsd:boolean"/>
		<xsd:attribute name="provider" type="xsd:string"/>
		<xsd:attribute name="website" type="xsd:anyURI" use="optional"/>
	</xsd:complexType>

	<xsd:element name="FindbugsPlugin" type="FindBugsPluginType"/>

</xsd:schema>

=== mebigfatguy/fb-contrib/etc/findbugs.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Plugin descriptor for fb-contrib plugin. This plugin is enabled by default. -->
<FindbugsPlugin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="findbugsplugin.xsd" pluginid="com.mebigfatguy.fbcontrib" defaultenabled="true"
	provider="fb-contrib project" website="http://fb-contrib.sourceforge.net">

	<!-- Passes -->

	<OrderingConstraints>
		<SplitPass>
			<Earlier class="com.mebigfatguy.fbcontrib.collect.CollectStatistics" />
			<LaterCategory name="reporting" spanplugins="true" />
		</SplitPass>
		<SplitPass>
            <Earlier class="com.mebigfatguy.fbcontrib.collect.CollectMethodsReturningImmutableCollections" />
            <LaterCategory name="reporting" spanplugins="true" />
        </SplitPass>
		
	</OrderingConstraints>

	<!-- Detectors -->

<!-- COMMENT OUT FOR RELEASE -->

    <Detector class="com.mebigfatguy.fbcontrib.debug.OCSDebugger" speed="fast"/>

    <Detector class="com.mebigfatguy.fbcontrib.detect.ClassEnvy" speed="fast" reports="CE_CLASS_ENVY" disabled="true" />
    
    <Detector class="com.mebigfatguy.fbcontrib.detect.BloatedSynchronizedBlock" speed="fast" reports="BSB_BLOATED_SYNCHRONIZED_BLOCK" hidden="true" /> 

    <Detector class="com.mebigfatguy.fbcontrib.detect.StutteredMethodArguments" speed="fast" reports="SMA_STUTTERED_METHOD_ARGUMENTS" hidden="true" /> 
    
    <Detector class="com.mebigfatguy.fbcontrib.detect.StackedTryBlocks" speed="fast" reports="STB_STACKED_TRY_BLOCKS" />
    
    <Detector class="com.mebigfatguy.fbcontrib.detect.BloatedAssignmentScope" speed="fast" reports="BAS_BLOATED_ASSIGNMENT_SCOPE" hidden="true" />

<!-- COMMENT OUT FOR RELEASE -->

	<Detector class="com.mebigfatguy.fbcontrib.collect.CollectStatistics" speed="fast" reports="" hidden="true" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering" speed="fast" reports="ISB_INEFFICIENT_STRING_BUFFERING,ISB_EMPTY_STRING_APPENDING,ISB_TOSTRING_APPENDING" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SyncCollectionIterators" speed="slow" reports="SCI_SYNCHRONIZED_COLLECTION_ITERATORS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.CyclomaticComplexity" speed="slow" reports="CC_CYCLOMATIC_COMPLEXITY" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.OverlyConcreteParameter" speed="slow" reports="OCP_OVERLY_CONCRETE_PARAMETER" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ListIndexedIterating" speed="moderate" reports="LII_LIST_INDEXED_ITERATING" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UnrelatedCollectionContents" speed="fast" reports="UCC_UNRELATED_COLLECTION_CONTENTS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.DeclaredRuntimeException" speed="fast" reports="DRE_DECLARED_RUNTIME_EXCEPTION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.LiteralStringComparison" speed="fast" reports="LSC_LITERAL_STRING_COMPARISON" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.PartiallyConstructedObjectAccess" speed="fast" reports="PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.DubiousListCollection" speed="fast" reports="DLC_DUBIOUS_LIST_COLLECTION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ParallelLists" speed="fast" reports="PL_PARALLEL_LISTS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.FinalParameters" speed="slow" reports="FP_FINAL_PARAMETERS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.AbstractClassEmptyMethods" speed="fast" reports="ACEM_ABSTRACT_CLASS_EMPTY_METHODS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ManualArrayCopy" speed="fast" reports="MAC_MANUAL_ARRAY_COPY" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.FloatingPointLoops" speed="fast" reports="FPL_FLOATING_POINT_LOOPS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NonCollectionMethodUse" speed="fast" reports="NCMU_NON_COLLECTION_METHOD_USE" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ConfusingAutoboxedOverloading" speed="fast" reports="CAO_CONFUSING_AUTOBOXED_OVERLOADING" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.AbnormalFinallyBlockReturn" speed="fast" reports="AFBR_ABNORMAL_FINALLY_BLOCK_RETURN" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.StaticMethodInstanceInvocation" speed="fast" reports="SMII_STATIC_METHOD_INSTANCE_INVOCATION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SpuriousThreadStates" speed="fast" reports="STS_SPURIOUS_THREAD_STATES" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NeedlessAutoboxing" speed="fast"
		reports="NAB_NEEDLESS_AUTOBOXING_CTOR,NAB_NEEDLESS_BOXING_STRING_CTOR,NAB_NEEDLESS_AUTOBOXING_VALUEOF,NAB_NEEDLESS_BOXING_PARSE,NAB_NEEDLESS_BOXING_VALUEOF,NAB_NEEDLESS_BOX_TO_UNBOX,NAB_NEEDLESS_BOX_TO_CAST,NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UnnecessaryStoreBeforeReturn" speed="fast" reports="USBR_UNNECESSARY_STORE_BEFORE_RETURN" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.CopiedOverriddenMethod" speed="fast" reports="COM_COPIED_OVERRIDDEN_METHOD" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ArrayBasedCollections" speed="fast" reports="ABC_ARRAY_BASED_COLLECTIONS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.OrphanedDOMNode" speed="fast" reports="ODN_ORPHANED_DOM_NODE" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.AbstractOverriddenMethod" speed="fast" reports="AOM_ABSTRACT_OVERRIDDEN_METHOD" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.CustomBuiltXML" speed="fast" reports="CBX_CUSTOM_BUILT_XML" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ConstantListIndex" speed="fast" reports="CLI_CONSTANT_LIST_INDEX" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SloppyClassReflection" speed="fast" reports="SCR_SLOPPY_CLASS_REFLECTION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.ArrayWrappedCallByReference" speed="fast" reports="AWCBR_ARRAY_WRAPPED_CALL_BY_REFERENCE" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SluggishGui" speed="fast" reports="SG_SLUGGISH_GUI" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NeedlessInstanceRetrieval" speed="fast" reports="NIR_NEEDLESS_INSTANCE_RETRIEVAL" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.DateComparison" speed="fast" reports="DDC_DOUBLE_DATE_COMPARISON" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SuspiciousWaitOnConcurrentObject" speed="fast" reports="SWCO_SUSPICIOUS_WAIT_ON_CONCURRENT_OBJECT" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.JDBCVendorReliance" speed="fast" reports="JVR_JDBC_VENDOR_RELIANCE" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.PossibleMemoryBloat" speed="fast" reports="PMB_POSSIBLE_MEMORY_BLOAT,PMB_INSTANCE_BASED_THREAD_LOCAL" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.LocalSynchronizedCollection" speed="moderate" reports="LSYC_LOCAL_SYNCHRONIZED_COLLECTION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.FieldCouldBeLocal" speed="slow" reports="FCBL_FIELD_COULD_BE_LOCAL" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NonOwnedSynchronization" speed="fast" reports="NOS_NON_OWNED_SYNCHRONIZATION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NonRecycleableTaglibs" speed="fast" reports="NRTL_NON_RECYCLEABLE_TAG_LIB" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.Section508Compliance" speed="fast"
		reports="S508C_NULL_LAYOUT,S508C_NO_SETLABELFOR,S508C_NO_SETSIZE,S508C_NON_ACCESSIBLE_JCOMPONENT,S508C_SET_COMP_COLOR,S508C_NON_TRANSLATABLE_STRING,S508C_APPENDED_STRING" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UseEnumCollections" speed="fast" reports="UEC_USE_ENUM_COLLECTIONS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SQLInLoop" speed="fast" reports="SIL_SQL_IN_LOOP" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.NeedlessMemberCollectionSynchronization" speed="moderate" reports="NMCS_NEEDLESS_MEMBER_COLLECTION_SYNCHRONIZATION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.InheritanceTypeChecking" speed="moderate" reports="ITC_INHERITANCE_TYPE_CHECKING" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.StaticArrayCreatedInMethod" speed="fast" reports="SACM_STATIC_ARRAY_CREATED_IN_METHOD" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.PossiblyRedundantMethodCalls" speed="fast" reports="PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UseToArray" speed="fast" reports="UTA_USE_TO_ARRAY" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.LostExceptionStackTrace" speed="moderate" reports="LEST_LOST_EXCEPTION_STACK_TRACE" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UseCharacterParameterizedMethod" speed="fast" reports="UCPM_USE_CHARACTER_PARAMETERIZED_METHOD" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.TailRecursion" speed="fast" reports="TR_TAIL_RECURSION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.UnrelatedReturnValues" speed="fast" reports="URV_UNRELATED_RETURN_VALUES,URV_CHANGE_RETURN_TYPE,URV_INHERITED_METHOD_WITH_RELATED_TYPES" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.PossibleIncompleteSerialization" speed="fast" reports="PIS_POSSIBLE_INCOMPLETE_SERIALIZATION" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SuspiciousComparatorReturnValues" speed="fast" reports="SC_SUSPICIOUS_COMPARATOR_RETURN_VALUES" />

	<Detector class="com.mebigfatguy.fbcontrib.detect.SillynessPotPourri" speed="fast"
